### ISSUE TITLE
Prevent cleartext traffic downgrade

### ISSUE THREAD

**Issue by leto** [MyHush/SilentDragonAndroid#71]
TOB-ZEC-005 from https://github.com/trailofbits/publications/blob/master/reviews/zecwallet.pdf

```
change the android: usesCleartextTraffic setting to false . This would
prevent any regressions to unencrypted web protocols.
```

**Comment by leto** [comment]
We use android sdk version 28 which defaults this to `true` so we are good:

```
android:usesCleartextTraffic
Indicates whether the app intends to use cleartext network traffic, such as cleartext HTTP. The default value for apps that target API level 27 or lower is "true". Apps that target API level 28 or higher default to "false".
```

as per https://developer.android.com/guide/topics/manifest/application-element

**Comment by leto** [comment]
This is actually set to true in app/src/main/AndroidManifest.xml

**Comment by leto** [comment]
My guess is that this is needed to allow SDA to pair to a local wallet on the local LAN without needing a valid SSL cert, which would be prevent average users from being able to pair their mobile app. Changing this setting to false needs to see how that affects pairing mobile apps locally. When the wormhole is used, that always uses TLS so that use case won't be affected by this.

**Comment by jahway603** [comment]
@leto Yeah, reading about this had to do with HTTP vs HTTPS. I was trying to determine which was being used for "wss://wormhole.myhush.org:443", but was not sure.

**Comment by jahway603** [comment]
@leto Just stumbled on this [ https://developer.android.com/training/articles/security-config ] and am looking at an example of it now. This might be the solution to this :+1:

**Comment by jahway603** [comment]
@leto Good to know the difference between wss and ws. Yeah, this is a funky issue and, after further looking into Android's Network Security Configuration, this config is only supported in Android 7+, so would only be a solution if we increased our minSdkVersion to that or higher. Additonally, this [NCC Group article](https://www.nccgroup.com/uk/about-us/newsroom-and-events/blogs/2017/november/bypassing-androids-network-security-configuration/) discusses how to bypass it. Since we are not using HTTP and only using HTTPS then I am closing this bug.

**Comment by leto** [comment]
@jahway603 agreed, thanks for verifying things. We never use HTTP and this is basically a false positive caused by automated software scanners and the fact that Android API is funky as hell
